elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./../elasticsearch-data:/usr/share/elasticsearch/data
    - ./elasticsearch/config:/usr/share/elasticsearch/config

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
