FROM elasticsearch:2

RUN /usr/share/elasticsearch/bin/plugin install --batch license
#RUN /usr/share/elasticsearch/bin/plugin install --batch shield
RUN /usr/share/elasticsearch/bin/plugin install --batch watcher
RUN /usr/share/elasticsearch/bin/plugin install --batch royrusso/elasticsearch-HQ
